In [4]:
import logging
logging.basicConfig(filename='26feb.log',level=logging.INFO)

import numpy as np
list_ = [ '1','2','3','4','5']
array_list = np.array(object = list_)

In [16]:
# Ans no1

logging.info("difference between array and list")

'''   
In Python, list_ is a built-in data type for representing a collection of items, 
which can be of different data types, such as integers, strings, or even other lists. 
On the other hand, array_list is a data type provided by the NumPy library, 
which represents an array of homogeneous data type, such as integers or floating-point numbers.
'''


print("the list is",list_)
print("the numpy array is",array_list)

the list is ['1', '2', '3', '4', '5']
the numpy array is [1 2 3 4 5]


In [12]:
# Ans no2

logging.info("the data type of each and every element of both the variables list_ and array_list.")

list_ = [ '1','2','3','4','5']
array_list = np.array(object = list_)

for i in list_:
    print(type(i))

for i in array_list:
    print(type(i))    

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [19]:
# Ans no3

logging.info("answering the qus 3")

array_list = np.array(object = list_, dtype = int)

'''
Yes, there will be a difference in the data type of the elements 
present in list_ and array_list after arra_list is created using the np.array()
function with a dtype of int.

'''
for i in list_:
    print(type(i))

for i in array_list:
    print(type(i))  

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


In [24]:
# Ans no4

import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

# shape  will return the shape of the num_array
print(num_array.shape)

# size  will return the size of the num_array
print(num_array.size)


(2, 3)
6


In [27]:
# Ans no5

logging.info("creating numpy array of 3*3 matrix containing zeros only")

arr=np.zeros((3,3))
print(arr)
print(arr.shape)
print(arr.size)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
(3, 3)
9


In [30]:
# Ans no6

logging.info("Creating an identity matrix of shape (5,5) using numpy functions")

# creating using numpy function
arrd=np.eye(5,5)
print(arrd)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
